spring.application.name=bibliotekssystem

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.security.user.name=admin
spring.security.user.password=admin123
spring.cache.type=simple
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.config.import=optional:vault://
spring.cloud.vault.uri=http://localhost:8200
spring.cloud.vault.token=root
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.application-name=library-api